# Generated by Django 5.1.4 on 2024-12-13 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grievance',
            name='assigned_to',
        ),
        migrations.AlterField(
            model_name='grievance',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.category'),
        ),
    ]
