# Generated by Django 5.1.4 on 2024-12-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_grievance_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='category',
            field=models.CharField(default='security', max_length=200),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='department',
            field=models.CharField(default='Technical', max_length=200),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='user',
            field=models.CharField(default='anonyms', max_length=200),
        ),
    ]
