# Generated by Django 5.1.4 on 2024-12-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_grievance_category_alter_grievance_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(default='', max_length=50),
        ),
    ]
